# Generated by Django 5.0.3 on 2024-03-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HexColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyeColor', models.CharField(max_length=7)),
                ('skinColor', models.CharField(max_length=7)),
                ('hairColor', models.CharField(max_length=7)),
            ],
        ),
    ]
