# Generated by Django 5.0.3 on 2024-03-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfieapp', '0002_hexcolors'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexcolors',
            name='chatResponse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
